# -*- coding: utf-8 -*-
"""bug_tracker.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oI1BBiZBd8zn21RkCUO4uQXpeOp5H-E8
"""

import pprint
import google.generativeai as palm

palm.configure(api_key='AIzaSyBSX1CACqI6S9OBscb7TT08INLWiw7deL0')

models = [m for m in palm.list_models() if 'generateText' in m.supported_generation_methods]
model = models[0].name
print(model)

input_code = input()
error = input()

prompt = """
I have coded a specific program and
I seem to have got an error while coding it

CODE:\n"""+input_code+"""\nERROR:\n"""+error+"""

Can you give an error Explanation?
Can you Suggest possible Fixes?
Can you Give the corrected code?
"""

print(prompt)

completion = palm.generate_text(
    model=model,
    prompt=prompt,
    temperature=0,
    # The maximum length of the response
    max_output_tokens=800,
)

print(completion.result)

output = completion.result
print(output)